I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 69, in script call
    call course_select
  File "game/Course_Select.rpy", line 5, in script
    call screen course_select_menu
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Users\\k1029\\AppData\\Roaming/RenPy/RenPy22-1647280797\\persistent'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 69, in script call
    call course_select
  File "game/Course_Select.rpy", line 5, in script
    call screen course_select_menu
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/ast.py", line 2015, in execute
    self.call("execute")
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/ast.py", line 2003, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/exports.py", line 3136, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/display/core.py", line 3962, in interact_core
    self.idle_frame(can_block, expensive)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/display/core.py", line 3451, in idle_frame
    renpy.persistent.check_update()
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/persistent.py", line 358, in check_update
    update()
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/persistent.py", line 395, in update
    save()
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/persistent.py", line 411, in save
    renpy.loadsave.location.save_persistent(data)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/savelocation.py", line 496, in save_persistent
    l.save_persistent(data)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/savelocation.py", line 351, in save_persistent
    safe_rename(fn_new, fn)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/loadsave.py", line 304, in safe_rename
    os.unlink(new)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Users\\k1029\\AppData\\Roaming/RenPy/RenPy22-1647280797\\persistent'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
RenPy22 1.0
Tue Mar 15 21:55:31 2022
